ESTABLISHMENT_OPTIONS = (
    'Adlaw Diversified Agri-Farm',
    'Capistrano Farm Resort',
    'Anpas Farm',
    'PICOS',
    'Dr. Basket',
    "El Ublo's Resort",
    'Nasuli Spring Resort',
    'Kaamulan Zoo',
    'Hauz Malibu',
    'Bom-Bom Hotel',
    'Kaamulan Suites',
    'Garden Suites',
    "Luisita's Suites",
    'Bukidnon Suites',
    'Yellow Petals',
    'Nomiarc',
    'Sildimco',
    'Abbey of Transfiguration',
    'Balay Ha Buksu',
    'Malaybalay Air BNB',
    'Villa Alemania Inn',
    'Plaza Park Inn',
    'OHfath Inn',
    'Bukidnon Fine Traveller Inn',
    'Mailaz Lodging',
    'Jaymond Lodge',
    'IMK Lodging Lodge',
    'A & L Visitors',
    'Waterpool Microtel',
    "Loiza's Pavilion",
    'Veranda',
    '1st Avenue Apartel',
    'Green Ridge Apartel',
    'JB Apartelle',
    'Dorf Transient Inn',
    'Ped Xing Transient',
    'Plaza View Tourist Inn',
    "0' Suites",
    'Bukidnon Breeze',
)

ESTABLISHMENT_OPTION_SET = frozenset(ESTABLISHMENT_OPTIONS)
