from django.urls import path

from audit.views import (
    ActivityLogClearView,
    ActivityLogExportView,
    ActivityLogListView,
    DataSubmissionListCreateView,
    DataSubmissionBulkExportView,
    DataSubmissionBulkStatusUpdateView,
    DataSubmissionPreviewView,
    DataSubmissionSendView,
    DataSubmissionStatusUpdateView,
    DataSubmissionTemplateDownloadView,
    DataSubmissionWorkspaceValidateView,
    DataSubmissionWorkspaceView,
    DataRequestCreateView,
    DataRequestHistoryView,
    DataRequestTargetListView,
    DashboardOverviewView,
    DashboardExcelPreviewView,
    RecycleBinEmptyView,
    RecycleBinListView,
    RecycleBinPurgeView,
    RecycleBinRestoreView,
    SubmissionNotificationListView,
    SubmissionNotificationReadAllView,
    SubmissionNotificationReadView,
    SystemBackupView,
    SystemImportView,
)

urlpatterns = [
    path('dashboard/overview/', DashboardOverviewView.as_view(), name='dashboard-overview'),
    path('dashboard/excel-preview/', DashboardExcelPreviewView.as_view(), name='dashboard-excel-preview'),
    path('data-submission-templates/<str:template_key>/', DataSubmissionTemplateDownloadView.as_view(), name='data-submission-template-download'),
    path('data-submissions/preview/', DataSubmissionPreviewView.as_view(), name='data-submissions-preview'),
    path('data-submissions/', DataSubmissionListCreateView.as_view(), name='data-submissions'),
    path('data-submissions/bulk-status/', DataSubmissionBulkStatusUpdateView.as_view(), name='data-submissions-bulk-status'),
    path('data-submissions/export/', DataSubmissionBulkExportView.as_view(), name='data-submissions-export'),
    path('data-submissions/<int:pk>/send/', DataSubmissionSendView.as_view(), name='data-submission-send'),
    path('data-submissions/<int:pk>/status/', DataSubmissionStatusUpdateView.as_view(), name='data-submission-status'),
    path('data-submissions/<int:pk>/workspace/', DataSubmissionWorkspaceView.as_view(), name='data-submission-workspace'),
    path('data-submissions/<int:pk>/workspace/validate/', DataSubmissionWorkspaceValidateView.as_view(), name='data-submission-workspace-validate'),
    path('data-request-targets/', DataRequestTargetListView.as_view(), name='data-request-targets'),
    path('data-requests/', DataRequestCreateView.as_view(), name='data-requests'),
    path('data-requests/history/', DataRequestHistoryView.as_view(), name='data-request-history'),
    path('submission-notifications/', SubmissionNotificationListView.as_view(), name='submission-notifications'),
    path('submission-notifications/read-all/', SubmissionNotificationReadAllView.as_view(), name='submission-notifications-read-all'),
    path('submission-notifications/<int:pk>/read/', SubmissionNotificationReadView.as_view(), name='submission-notifications-read'),
    path('activity-logs/', ActivityLogListView.as_view(), name='activity-logs'),
    path('activity-logs/clear/', ActivityLogClearView.as_view(), name='activity-logs-clear'),
    path('activity-logs/export/', ActivityLogExportView.as_view(), name='activity-logs-export'),
    path('recycle-bin/', RecycleBinListView.as_view(), name='recycle-bin'),
    path('recycle-bin/<int:pk>/restore/', RecycleBinRestoreView.as_view(), name='recycle-bin-restore'),
    path('recycle-bin/<int:pk>/purge/', RecycleBinPurgeView.as_view(), name='recycle-bin-purge'),
    path('recycle-bin/empty/', RecycleBinEmptyView.as_view(), name='recycle-bin-empty'),
    path('system/backup/', SystemBackupView.as_view(), name='system-backup'),
    path('system/import/', SystemImportView.as_view(), name='system-import'),
]
