services:
  - type: web
    name: citosis-pro
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn citosis_pro.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: citosis.onrender.com,citosis-1.onrender.com,citosis-pro.onrender.com,.onrender.com
      - key: APP_URL
        value: https://citosis.onrender.com
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: https://citosis.onrender.com,https://citosis-1.onrender.com,https://citosis-pro.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: TIME_ZONE
        value: Asia/Manila
      - key: USE_SQLITE
        value: "True"
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
