# Generated by Django 6.0.4 on 2026-04-23 16:56

from django.db import migrations, models


def migrate_legacy_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    legacy_role_map = {
        'Admin': 'Super Admin',
        'Manager': 'Reviewer',
        'Encoder': 'Reviewer',
        'Staff': 'User',
    }
    for legacy_role, next_role in legacy_role_map.items():
        User.objects.filter(role=legacy_role).update(role=next_role)


def reverse_legacy_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    reverse_role_map = {
        'Super Admin': 'Admin',
        'Reviewer': 'Manager',
        'User': 'Staff',
    }
    for next_role, legacy_role in reverse_role_map.items():
        User.objects.filter(role=next_role).update(role=legacy_role)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_roles, reverse_legacy_roles),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Reviewer', 'Reviewer'), ('Viewer', 'Viewer'), ('User', 'User')], default='User', max_length=20),
        ),
    ]
