# Generated by Codex on 2026-05-15

from django.db import migrations, models

DEFAULT_ESTABLISHMENT_OPTIONS = (
    'Adlaw Diversified Agri-Farm',
    'Capistrano Farm Resort',
    'Anpas Farm',
    'PICOS',
    'Dr. Basket',
    "El Ublo's Resort",
    'Nasuli Spring Resort',
    'Kaamulan Zoo',
    'Hauz Malibu',
    'Bom-Bom Hotel',
    'Kaamulan Suites',
    'Garden Suites',
    "Luisita's Suites",
    'Bukidnon Suites',
    'Yellow Petals',
    'Nomiarc',
    'Sildimco',
    'Abbey of Transfiguration',
    'Balay Ha Buksu',
    'Malaybalay Air BNB',
    'Villa Alemania Inn',
    'Plaza Park Inn',
    'OHfath Inn',
    'Bukidnon Fine Traveller Inn',
    'Mailaz Lodging',
    'Jaymond Lodge',
    'IMK Lodging Lodge',
    'A & L Visitors',
    'Waterpool Microtel',
    "Loiza's Pavilion",
    'Veranda',
    '1st Avenue Apartel',
    'Green Ridge Apartel',
    'JB Apartelle',
    'Dorf Transient Inn',
    'Ped Xing Transient',
    'Plaza View Tourist Inn',
    "0' Suites",
    'Bukidnon Breeze',
)


def seed_default_establishments(apps, schema_editor):
    Establishment = apps.get_model('accounts', 'Establishment')
    for name in DEFAULT_ESTABLISHMENT_OPTIONS:
        Establishment.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'establishments',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_default_establishments, migrations.RunPython.noop),
    ]
