# Generated by Django 6.0.4 on 2026-04-23 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_reviewed_status_to_approved(apps, schema_editor):
    DataSubmission = apps.get_model('audit', 'DataSubmission')
    DataSubmission.objects.filter(status='Reviewed').update(status='Approved')


def reverse_approved_status_to_reviewed(apps, schema_editor):
    DataSubmission = apps.get_model('audit', 'DataSubmission')
    DataSubmission.objects.filter(status='Approved').update(status='Reviewed')


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_datasubmission_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datasubmission',
            name='admin_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datasubmission',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('In Review', 'In Review'), ('Needs Revision', 'Needs Revision'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.RunPython(migrate_reviewed_status_to_approved, reverse_approved_status_to_reviewed),
        migrations.CreateModel(
            name='SubmissionNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status_snapshot', models.CharField(blank=True, max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_submission_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_notifications', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='audit.datasubmission')),
            ],
            options={
                'db_table': 'submission_notifications',
                'ordering': ['is_read', '-created_at', '-id'],
            },
        ),
    ]
