# Generated by Django 6.0.4 on 2026-04-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_datasubmission_admin_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasubmission',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='datasubmission',
            name='mapping_profile_key',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
