# Generated by Django 6.0.4 on 2026-04-23 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_datasubmission_column_mapping_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datasubmission',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasubmission',
            name='last_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_data_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasubmission',
            name='review_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
