# Generated by Codex on 2026-04-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_datasubmission_last_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionnotification',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='audit.datasubmission'),
        ),
        migrations.AddField(
            model_name='submissionnotification',
            name='notification_type',
            field=models.CharField(choices=[('Submission', 'Submission'), ('Data Request', 'Data Request')], default='Submission', max_length=30),
        ),
        migrations.AddField(
            model_name='submissionnotification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
