# Generated by Codex on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_data_request_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionnotification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('Submission', 'Submission'),
                    ('Data Request', 'Data Request'),
                    ('User Registration', 'User Registration'),
                ],
                default='Submission',
                max_length=30,
            ),
        ),
    ]
